apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfba-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pfba-backend
  template:
    metadata:
      labels:
        app: pfba-backend
    spec:
      containers:
        - name: backend
          image: personal-financial-behavior-analyzer-backend:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/pfba"
            - name: SPRING_DATASOURCE_USERNAME
              value: "pfba_user"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: GEMINI_API_KEY


          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10

